name: Deploy Pipeline

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: "Enter artifact name (e.g. build-45.zip)"
        required: true

jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Download artifact from S3
        run: |
          aws s3 cp s3://${{ secrets.ARTIFACT_BUCKET }}/builds/${{ github.event.inputs.build_id }} .

      - name: Unzip
        run: unzip *.zip

      - name: Deploy to Dev S3
        run: |
          aws s3 sync dist s3://${{ secrets.DEV_BUCKET }} --delete

      - name: Invalidate Dev CDN
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DEV_DIST_ID }} \
            --paths "/*"

  deploy-uat:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: uat   # 🔐 approval

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Download artifact
        run: |
          aws s3 cp s3://${{ secrets.ARTIFACT_BUCKET }}/builds/${{ github.event.inputs.build_id }} .

      - name: Unzip
        run: unzip *.zip

      - name: Deploy to UAT
        run: |
          aws s3 sync dist s3://${{ secrets.UAT_BUCKET }} --delete

      - name: Invalidate UAT CDN
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.UAT_DIST_ID }} \
            --paths "/*"

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: prod  # 🔐 approval

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Download artifact
        run: |
          aws s3 cp s3://${{ secrets.ARTIFACT_BUCKET }}/builds/${{ github.event.inputs.build_id }} .

      - name: Unzip
        run: unzip *.zip

      - name: Deploy to Prod
        run: |
          aws s3 sync dist s3://${{ secrets.PROD_BUCKET }} --delete

      - name: Invalidate Prod CDN
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.PROD_DIST_ID }} \
            --paths "/*"
