name: Deploy Pipeline

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Set build id
        run: echo "BUILD_ID=build-${{ github.event.workflow_run.run_number }}.zip" >> $GITHUB_ENV

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.REGION }}

      - name: Download artifact
        run: |
          aws s3 cp s3://${{ vars.ARTIFACT_BUCKET }}/builds/${{ env.BUILD_ID }} .

      - name: Unzip
        run: unzip *.zip

      - name: Deploy to Dev
        run: aws s3 sync dist s3://${{ vars.DEV_BUCKET }} --delete

      - name: Invalidate Dev CDN
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.DEV_DIST_ID }} \
          --paths "/*"

  deploy-uat:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: uat   # 👈 approval here

    steps:
      - name: Set build id
        run: echo "BUILD_ID=build-${{ github.event.workflow_run.run_number }}.zip" >> $GITHUB_ENV

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.REGION }}

      - name: Download artifact
        run: |
          aws s3 cp s3://${{ vars.ARTIFACT_BUCKET }}/builds/${{ env.BUILD_ID }} .

      - name: Unzip
        run: unzip *.zip

      - name: Deploy to UAT
        run: aws s3 sync dist s3://${{ vars.UAT_BUCKET }} --delete

      - name: Invalidate UAT CDN
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.UAT_DIST_ID }} \
          --paths "/*"

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: prod   # 👈 approval here

    steps:
      - name: Set build id
        run: echo "BUILD_ID=build-${{ github.event.workflow_run.run_number }}.zip" >> $GITHUB_ENV

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.REGION }}

      - name: Download artifact
        run: |
          aws s3 cp s3://${{ vars.ARTIFACT_BUCKET }}/builds/${{ env.BUILD_ID }} .

      - name: Unzip
        run: unzip *.zip

      - name: Deploy to Prod
        run: aws s3 sync dist s3://${{ vars.PROD_BUCKET }} --delete

      - name: Invalidate Prod CDN
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.PROD_DIST_ID }} \
          --paths "/*"
