name: Deploy Pipeline

permissions:
  id-token: write
  contents: read

on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:

  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Set build id
        run: echo "BUILD_ID=build-${{ github.event.workflow_run.run_number }}.zip" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.REGION }}

      - run: |
          aws s3 cp s3://${{ vars.ARTIFACT_BUCKET }}/builds/${{ env.BUILD_ID }} .

      - run: unzip *.zip

      - run: aws s3 sync dist s3://${{ vars.DEV_BUCKET }} --delete

      - run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.DEV_DIST_ID }} \
          --paths "/*"

  deploy-uat:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Set build id
        run: echo "BUILD_ID=build-${{ github.event.workflow_run.run_number }}.zip" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.REGION }}

      - run: |
          aws s3 cp s3://${{ vars.ARTIFACT_BUCKET }}/builds/${{ env.BUILD_ID }} .

      - run: unzip *.zip

      - run: aws s3 sync dist s3://${{ vars.UAT_BUCKET }} --delete

      - run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.UAT_DIST_ID }} \
          --paths "/*"

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Set build id
        run: echo "BUILD_ID=build-${{ github.event.workflow_run.run_number }}.zip" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.REGION }}

      - run: |
          aws s3 cp s3://${{ vars.ARTIFACT_BUCKET }}/builds/${{ env.BUILD_ID }} .

      - run: unzip *.zip

      - run: aws s3 sync dist s3://${{ vars.PROD_BUCKET }} --delete

      - run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.PROD_DIST_ID }} \
          --paths "/*"