name: CI Build

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      # 🔍 SONAR SCAN (WORKING)
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=thirupathi-reddy
            -Dsonar.projectKey=thirupathi-reddy_healthcare-frontend
            -Dsonar.sources=.
            -Dsonar.exclusions=prisma/migrations/**,prisma/seed.ts

      - name: Create env
        run: echo "VITE_BASE_URL=${{ vars.DEV_VITE_BASE_URL }}" > .env

      - name: Build
        run: npm run build

 

      - name: Zip build
        run: zip -r build-${{ github.run_number }}.zip dist

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp build-${{ github.run_number }}.zip \
          s3://${{ vars.ARTIFACT_BUCKET }}/builds/

      - name: Output artifact
        run: echo "Artifact = build-${{ github.run_number }}.zip"